# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20181116_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
    ]
